version = 0.1

extensions = ['chomp@0.1:footprint', 'chomp@0.1:npm']

default-task = 'test'

[server]
port = 8080
root = "."

[[task]]
name = 'bench'
run = 'chomp -c bench'

[[task]]
name = 'bench:clear'
run = 'rm -rf bench/results'

[[task]]
name = 'build'
targets = ['dist/es-module-shims.js', 'dist/es-module-shims.wasm.js']
deps = ['src/*.js', 'npm:install', 'README.md']
run = 'rollup -c'

[[task]]
target = 'README.md'
dep = 'package.json'
engine = 'node'
run = '''
  import { readFileSync, writeFileSync } from 'fs';
  const { version } = JSON.parse(readFileSync(process.env.DEP, 'utf8'));
  const source = readFileSync(process.env.TARGET, 'utf8')
    .replace(/es-module-shims@\d+.\d+.\d+/g, `es-module-shims@${version}`);
  writeFileSync(process.env.TARGET, source);
'''

[[task]]
target = 'dist/hot.js'
run = 'cp src/hot-reload.js dist/hot.js'

[[task]]
name = 'footprint'
deps = ['dist/es-module-shims.js', 'dist/es-module-shims.wasm.js', 'dist/hot.js']
template = 'footprint'

[[task]]
name = 'test'
dep = 'test:'

[[task]]
name = 'test:#'
serial = true
deps = ['npm:install', 'dist/es-module-shims.js', 'dist/es-module-shims.wasm.js', 'test/test-#.html']
run = 'node test/server.mjs test-${{ MATCH }}'
